version: '3.7'

services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    ports:
      - "8080:80"
      - "8443:443"
      - "5900:5900"
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Etc/UTC
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
